security:

    encoders:
       OC\UserBundle\Entity\User: sha512              
       
    role_hierarchy:
      ROLE_ADMIN:        [ROLE_AUTEUR, ROLE_MODERATEUR]
      ROLE_SUPER_ADMIN:  [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      main: 
          id: fos_user.user_provider.username

    provider: main
    
    firewalls:
      dev:
        pattern: ^/(_profiler|wdt|css|images|js)/
        security: false
      main:
        pattern:    ^/
        anonymous: true
        form_login:
          login_path: fos_user_security_login
          check_path: fos_user_security_check
        logout:
          path:   fos_user_security_logout
          target: /platform
        remember_me:
          secret:  secret          

    access_control:
      #- { path: ^/login, roles: IS_AUTHENTUCATED_ANONYMOUSLY, requires_channer: https }
      - { path: ^/admin,roles:ROLE_ADMIN }  