oc_platform_home:
    path:     /{page}
    defaults: { _controller: OCPlatformBundle:Advert:index, page: 1}
    requirements:
        page: \d*
    
oc_platform_view:
    path:     /advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view}
    requirements:
        id: \d+
    
oc_platform_add:
    path:     /add
    defaults: { _controller: OCPlatformBundle:Advert:add}  
    
oc_platform_edit:
    path:    /edit/{id}
    defaults: { _controller: OCPlatformBundle:Advert:edit}
    requirements:
        id: \d+

oc_platform_delete:
    path:    /delete/{id}
    defaults: { _controller: OCPlatformBundle:Advert:delete}
    requirements:
        id: \d+ 

oc_platform_purger:
    path:     /purge/{days}
    defaults: { _controller: OCPlatformBundle:Advert:purge}
    requirements:
        days: \d+

oc_platform_apply:
    path:    /apply/{id}
    defaults: { _controller: OCPlatformBundle:Advert:apply}
    requirements:
        id: \d+
        
oc_platform_user:
    path:     /user/{id}
    defaults: { _controller: OCUserBundle:User:user}
    requirements:
        id: \d+
        
oc_platform_paramconverter:
  path: /test/{json}
  defaults:
    _controller: "OCPlatformBundle:Advert:ParamConverter"                                    